___

<a href="https://lms.clarusway.com/course/view.php?id=37"><img align="center" src="https://i.ibb.co/6Z5pQxD/lmss.png" alt="Open in Clarusway LMS" width="70" height="200" title="Open Clarusway Learning Management Sytem"></a>

<a href="https://github.com/clarusway/DS-DE-0322-Students/blob/main/3-%20Classes%26Labs/3-DVwPY/DVwPy_S06_Capstone_Project%20(Bike%20Store%20Sharing).ipynb"><img align="left" src="https://i.ibb.co/n3HWyQX/github-logo.png" alt="Open in Clarusway GitHub" width="100" height="150" title="Open and Execute in Clarusway GitHub Repository"></a>

<a href="https://nbviewer.org/github/4dsolutions/clarusway_data_analysis/blob/main/DVwPY_S6/6-DVwPy%20Capstone%20%28Bike%20Store%20Sharing%29.ipynb"><img align="right" src="https://i.ibb.co/48wtV8c/nbviewer-badge.png" alt="Open in nbviewer" width="130" height="200" title="Open and Execute in nbviewer"></a><br/>
___

<a href="https://clarusway.com/"><img align="center" src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" alt="CLRSWY" width="450" height="200" title="Welcome to Place Where You can Reinvent Yourself"></a><br/>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:120%; text-align:center; border-radius:10px 10px;">Way to Reinvent Yourself</p>

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [1]:
# YOUR CODE IS HERE

import numpy as np

### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [2]:
# YOUR CODE IS HERE
my_list = [5, 10, 15, 20, 25]
np.array(my_list)


array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros. 

In [3]:
# YOUR CODE IS HERE
np.zeros((5,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [4]:
# YOUR CODE IS HERE
np.ones((4, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [5]:
# YOUR CODE IS HERE
my_array=np.ones((4, 4), dtype=int)
for i in range(len(my_array)):
    my_array[i] = 7
print(my_array)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


### 6. Create the previous array above by full() method.

In [6]:
# YOUR CODE IS HERE
import numpy as np
np.full([4,4],7,dtype=int)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive). 

In [7]:
# YOUR CODE IS HERE
np.arange(2, 17, 2)


array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [8]:
# YOUR CODE IS HERE
np.arange(0,25).reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [9]:
# YOUR CODE IS HERE
np.linspace(0,25,num=25,dtype=int).reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 25]])

### 10. Create randomly 5 numbers with numpy.

In [10]:
# YOUR CODE IS HERE
np.random.random(5)



array([0.69118028, 0.99156247, 0.87738381, 0.63292482, 0.02083801])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [11]:
# YOUR CODE IS HERE

np.random.randn(5,5)

array([[ 0.30944693,  1.52620053, -0.72420514,  0.16271992,  0.32413796],
       [ 0.47804642,  0.88516861,  0.3882042 ,  0.13603666,  1.2527807 ],
       [-0.80740451,  1.03878637,  1.49287463, -0.50741737,  1.36610838],
       [-0.1423116 , -1.15262923,  0.47026244, -1.54067041,  1.20681223],
       [ 0.79169186,  1.24780045, -0.83949494,  1.60542623, -0.44377003]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [12]:
# YOUR CODE IS HERE

np.random.randint(20, 51, size=(3, 4))

array([[34, 37, 33, 20],
       [46, 30, 38, 27],
       [28, 30, 46, 39]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [13]:
from os import name
# YOUR CODE IS HERE

np.random.randint(100,size=48)


array([16, 19, 99, 21, 75, 67, 16,  2, 58, 62,  3, 45, 66, 33, 78, 82, 15,
       49, 66, 29, 20, 61, 76, 90, 10, 20, 50, 77, 67, 40, 56, 25,  8, 24,
       69,  8, 42, 86, 25,  8, 94, 55, 65, 41, 31, 94, 23, 17])

In [14]:
# YOUR CODE IS HERE (RESHAPING WITH NUM)

np.random.randint(100,size=48).reshape(6,8)

array([[ 0, 11, 32, 33, 25, 78, 44, 89],
       [51, 37, 78, 50, 58, 72, 37, 48],
       [30, 56, 74, 53, 17, 71, 54, 74],
       [51, 35, 59, 73,  8, 74, 38, 62],
       [53, 87, 11, 37, 93, 50,  3, 62],
       [ 0, 29, 40, 43, 69, 76,  7, 34]])

In [15]:
# YOUR CODE IS HERE (RESHAPING WITH -1)
np.random.randint(100,size=48).reshape(6,-1)


array([[91, 94, 68, 25, 65, 24, 42, 41],
       [56, 15, 25, 38, 47, 58, 51, 13],
       [29, 83, 29, 12, 95, 38, 80, 22],
       [23, 77, 72, 29, 50, 84, 41, 86],
       [72, 78, 58, 59, 97, 84, 38, 88],
       [31, 73, 13, 63, 47, 89, 37, 85]])

In [16]:
# YOUR CODE IS HERE (RESHAPING WITH -1)
np.random.randint(100,size=48).reshape(4,-1,)


array([[44,  7, 78, 39, 16, 62, 94,  4, 84, 37, 76, 92],
       [41, 99,  4,  7, 22,  4, 43,  1, 19, 40, 14,  3],
       [34, 36, 78, 73, 29, 11, 17, 75, 68, 38,  7, 15],
       [94, 75, 97,  7, 73, 19, 78, 66, 66, 50, 78, 43]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [17]:
# YOUR CODE IS HERE 
mat=np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [18]:
# YOUR CODE IS HERE 
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [19]:
# YOUR CODE IS HERE 
mat[0:,0]

array([ 1,  5,  9, 13])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [20]:
# YOUR CODE IS HERE 
mat[1,0::2]

array([5, 7])

### 17.Assign 77 to every cell in 3rd column.

In [21]:
# YOUR CODE IS HERE 
mat[0:,2]=77

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [22]:
# YOUR CODE IS HERE 
mat[np.array([1,3]),np.array([0,2])]

array([ 5, 77])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [23]:
# YOUR CODE IS HERE 
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [24]:
mat[1:4:2,0:4:2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [25]:
# LET US REMEMBER OUR ARRAY OF "mat" 
mat
# YOUR CODE IS HERE 



array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [26]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat" 

# YOUR CODE IS HERE 
mat[mat<10]
   


array([1, 2, 4, 5, 6, 8, 9])

In [27]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 
mat[mat>12]


array([77, 77, 77, 13, 14, 77, 16])

In [28]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 

mat[mat>12]+mat[mat<10]

array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [29]:
# YOUR CODE IS HERE 

arr_std=mat[mat>12]+mat[mat<10]
arr_std.std()

29.700546274093877

### 22. Get the sum of the 2nd column in the original "mat".

In [30]:
# LET US REMEMBER OUR ARRAY OF "mat" 
mat
# YOUR CODE IS HERE 


array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [31]:
# LET US OBTAIN THE ORIGINAL ARRAY OF "mat" 

# YOUR CODE IS HERE 
mat[:,2]=[3,7,11,15]
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [32]:
# YOUR CODE IS HERE 
np.sum(mat[:,1])


32

### 23. Get the median, mean and std of 3rd column in "mat".

In [33]:
# LET US REMEMBER OUR ARRAY OF "mat" 
mat
# YOUR CODE IS HERE 



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [34]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE 

# YOUR CODE IS HERE 
a=mat[:,2].reshape(4,1)
a



array([[ 3],
       [ 7],
       [11],
       [15]])

In [35]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW? 

# YOUR CODE IS HERE 
b=mat[2,:]
b


array([ 9, 10, 11, 12])

In [36]:
# LET US GET MEDIAN VALUE 

# YOUR CODE IS HERE 
print(d)
print(c)


NameError: name 'd' is not defined

In [41]:
# LET US GET MEAN VALUE 

# YOUR CODE IS HERE 
e=np.mean(mat[2,:])
k=np.mean(mat[:,2])

In [42]:
print(k)
print(e)

9.0
10.5


In [43]:
# LET US GET STANDART DEVIATION (std) VALUE 

# YOUR CODE IS HERE 
g=np.std(mat[:,2])
h=np.std(mat[2,:])



In [44]:
print(g)
print(h)

4.47213595499958
1.118033988749895


## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [45]:
# YOUR CODE IS HERE 
import pandas as pd


### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

In [46]:
#burda ne yaziyordu

In [47]:
# LET US READ Salaries.csv 

# YOUR CODE IS HERE 

data=pd.read_csv('Salaries.csv')
pd.DataFrame(data)

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [48]:
# LET US LOOK AT THE FIRST 5 ROWS 

# YOUR CODE IS HERE 
data.head(5)


Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [49]:
# LET US GET A SAMPLE 

# YOUR CODE IS HERE 
data.sample(5)


Id       EmployeeName                     JobTitle    BasePay  \
80322  80323  Jessica P Buendia                   Manager II  112552.06   
37032  37033    Yusufu Caungula                  Firefighter  110847.09   
84574  84575   Yelena V Zalkina  Senior Physician Specialist   98799.80   
92327  92328  Anthoney N Bryant       Patient Care Assistant   68391.01   
79134  79135      Keith A Sovig             Police Officer 3  123471.17   

       OvertimePay  OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
80322         0.00      0.00  45254.31  112552.06         157806.37  2013   
37032     63300.99  16531.14  39216.96  190679.22         229896.18  2012   
84574         0.00   4940.08  27045.50  103739.88         130785.38  2013   
92327      3867.90    250.00  27231.83   72508.91          99740.74  2013   
79134      5755.57    851.06  37025.18  130077.80         167102.98  2013   

       Notes         Agency  Status  
80322    NaN  San Francisco     NaN  
37032    NaN  San Francisco     NaN  
84574    NaN  San Francisco     NaN  
92327    NaN  San Francisco     NaN  
79134    NaN  San Francisco     NaN

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [50]:
# YOUR CODE IS HERE 

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [51]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS  

# YOUR CODE IS HERE 
data.describe()


Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448840    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [52]:
# YOUR CODE IS HERE 

data['Year'].value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

In [53]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 
data['Year'].nunique()


4

In [54]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 
data['Year'].unique()


array([2011, 2012, 2013, 2014], dtype=int64)

### Print out max and avg values in the column of "Totalpay".

In [55]:
# LET US FIND THE MAXIMUM TOTALPAY

# YOUR CODE IS HERE 

data['TotalPay'].max()

567595.43

In [56]:
# LET US FIND THE AVERAGE TOTALPAY

# YOUR CODE IS HERE 
data['TotalPay'].mean()


74768.32197169267

### How many records in the TotalPay column are there bigger than avg TotalPay?

In [57]:
# YOUR CODE IS HERE 

data[data['TotalPay']>data['TotalPay'].mean()].value_counts()

Series([], dtype: int64)

Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [58]:
# YOUR CODE IS HERE 
data[data['TotalPay']>data['TotalPay'].mean()].count()


Id                  69489
EmployeeName        69489
JobTitle            69489
BasePay             69480
OvertimePay         69489
OtherPay            69489
Benefits            53642
TotalPay            69489
TotalPayBenefits    69489
Year                69489
Notes                   0
Agency              69489
Status                  0
dtype: int64

### How much does ALBERT PARDINI make money (including benefits)?

In [59]:
# YOUR CODE IS HERE 

data[(data['EmployeeName']=='ALBERT PARDINI')].TotalPayBenefits

2    335279.91
Name: TotalPayBenefits, dtype: float64

### Who is the lowest paid person?

In [60]:
# YOUR CODE IS HERE 

data[(data['BasePay']==0)].EmployeeName.tail(1)


148653    Joe Lopez
Name: EmployeeName, dtype: object

### What are the unique Jobs in dataset?

In [61]:
# YOUR CODE IS HERE 

data['JobTitle'].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

### List the top 3 least common Jobs in the dataset.

In [62]:
# YOUR CODE IS HERE 
data['JobTitle'].value_counts(ascending=False).tail(3)


COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: JobTitle, dtype: int64

### How many people earned more than avg in 2012?

In [121]:
# YOUR CODE IS HERE 
((data['Year'] == 2012) & (data["TotalPayBenefits"] > data['TotalPayBenefits'].mean())).sum()

20366

### How many people have a title of Manager in their jobs?

In [92]:
# USE APPLY FUNCTION FOR THIS QUESTION!

# YOUR CODE IS HERE 

len(data[data['JobTitle'].str.contains('Manager')])

3080

### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [104]:
# YOUR CODE IS HERE 

#sal_new = data[['Id','EmployeeName','JobTitle','TotalPay','TotalPayBenefits']].copy
sal_new=data.iloc[:,[0,1,2,7,8]].copy()
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [118]:
# YOUR CODE IS HERE 
sal_new1 = data.loc[:,['EmployeeName','JobTitle','TotalPay','TotalPayBenefits'].copy()]
sal_new1

EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

         TotalPay  TotalPayBenefits  
0       567595.43         567595.43  
1       538909.28         538909.28  
2       335279.91         335279.91  
3       332343.61         332343.61  
4       326373.19         326373.19  
...           ...               ...  
148649       0.00              0.00  
148650       0.00              0.00  
148651       0.00              0.00  
148652       0.00              0.00  
148653    -618.13           -618.13  

[148654 rows x 4 columns]

Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [123]:
# YOUR CODE IS HERE 
((data['EmployeeName']) & (data["TotalPayBenefits"] > data['TotalPayBenefits'].mean())).sum()

TypeError: unsupported operand type(s) for &: 'str' and 'bool'

Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________